### ISSUE TITLE
How to Create PEM-encoded RSA private key from raw modulus / exponent.

### ISSUE THREAD

**Issue by miter6** [JonathonReinhart/rawrsa#1]
Hi Jonathon,
    Thank for your routine,It save my a lot of time.

**Comment by JonathonReinhart** [comment]
I'm not sure what you're asking, exactly. 

> I get another problem that i have to generate the RSA private key from raw modulus and exponent.

While "generate" isn't the right word here, this is _exactly_ what this program does: convert a "raw" binary modulus into a typical key format.

> I think create PEM-encoded RSA private and public key from modulus and exponent is worth developing in the future.

This, along with the title of your issue is copy & pasted directly out of the description for this project:

> Create PEM-encoded RSA pubilc key from raw modulus / exponent

What exactly are you trying to do?  If you're trying to _generate_ an RSA keypair, there are many resources that tell you how to do this with OpenSSL:
- [Cryptography/Generate a keypair using OpenSSL](https://en.wikibooks.org/wiki/Cryptography/Generate_a_keypair_using_OpenSSL)

**Comment by JonathonReinhart** [comment]
And now you've deleted the rest of the text. Sigh.
